module.exports = {
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    OAUTH_CLIENT_CREATED: "OAUTH_CLIENT_CREATED",
    OAUTH_CLIENT_ERROR: "OAUTH_CLIENT_ERROR",
    OAUTH_CLIENT_DELETED: "OAUTH_CLIENT_DELETED",
    FETCH_MESSAGES_OK : "FETCH_MESSAGES_OK",
    FETCH_MESSAGES_ERROR : "FETCH_MESSAGES_OK",
    FETCH_ONE_MESSAGE_OK: "FETCH_ONE_MESSAGE_OK",
    SELECT_MESSAGE: "SELECT_MESSAGE",
    UNSELECT_MESSAGE: "UNSELECT_MESSAGE",
    FETCH_CONVERSATIONS_OK: "FETCH_CONVERSATIONS_OK",
    FETCH_CONVERSATIONS_ERROR: "FETCH_CONVERSATIONS_ERROR",
    FETCH_USER_PORTION_OK : "FETCH_USER_PORTION_OK",
    FETCH_USER_PORTION_ERROR: "FETCH_USER_PORTION_ERROR"
}