module.exports = {
    FETCH_MESSAGES_OK : "FETCH_MESSAGES_OK",
    FETCH_MESSAGES_ERROR : "FETCH_MESSAGES_OK",
    FETCH_ONE_MESSAGE_OK: "FETCH_ONE_MESSAGE_OK",
    SELECT_MESSAGE: "SELECT_MESSAGE",
    UNSELECT_MESSAGE: "UNSELECT_MESSAGE",
    FETCH_CONVERSATIONS_OK: "FETCH_CONVERSATIONS_OK",
    FETCH_CONVERSATIONS_ERROR: "FETCH_CONVERSATIONS_ERROR",
    FETCH_USER_PORTION_OK : "FETCH_USER_PORTION_OK",
    FETCH_USER_PORTION_ERROR: "FETCH_USER_PORTION_ERROR",
    CONVERSATION_POST_OK : "CONVERSATION_POST_OK",
    CONVERSATION_POST_ERROR: "CONSERSATION_POST_ERROR"
}